text_type should be a type alias, not a variable
# Example program
```python
import six
def hello(name: six.text_type) -> None:
    print(f"Hello {name}!")
hello("Johan")
```

# Before this change
```sh
(env) /t/dom $ mypy code.py
code.py:2: error: Variable "six.text_type" is not valid as a type
code.py:2: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
(env) /t/dom [1] $ fd six
```

# With this change in place
```sh
(env) /t/dom $ mypy code.py
Success: no issues found in 1 source file
(env) /t/dom $ 
```