Match assertIsInstance signature with isinstance
The old signature gave errors in use. For example, the following code:

    for cls in [RefSnpBlobs, SplitSnps, Vcf]: # All these are classes
                r = create_product(BuildFlavor.Production, run_id, ver, cls)
	        self.assertIsInstance(r, cls)

Yielded the following error:

    tests/test_factory.py:21: error: Argument 2 to "assertIsInstance" of "TestCase" has incompatible type "type"; expected "Union[Type[Any], Tuple[Type[Any], ...]]"

With the new type signature: `Union[type, Tuple[type, ...]]` lifted from the isinstance that code compiles fine. Since the docs say that the signature is the same as isinstance (https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIsInstance) I think this is OK.

I haven't tested this particular commit. I made the same changes in my local typeshed install and they worked -- but anyone merging this PR should double-check I didn't make some sort of typo.