builtins: complex doesn't define __complex__
```
~ λ python3.9
Python 3.9.0 (default, Oct  7 2020, 13:16:14)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> (1+4j).__complex__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'complex' object has no attribute '__complex__'
```