Remove uninstallable package fb303
The package fb303 does not have any files on PyPI. The last PyPI update
occurred on Jan 22, 2009. Further, trying to follow the links listed on
PyPI result in 404s.

https://pypi.org/project/fb303/

    $ pip install fb303
    ERROR: Could not find a version that satisfies the requirement fb303 (from versions: none)
    ERROR: No matching distribution found for fb303